name: aws-ci

on:
  push:
    branches:
      - main

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: ${{ secrets.test1 }}
        envkey_SECRET_KEY: ${{ secrets.test }}
        some_other_variable: foobar
        directory: .
        file_name: .env
  deploy-csv-loder:
    runs-on: ubuntu-latest
    # if: (github.ref == 'refs/heads/develop')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: print envs
        run: echo cat .env

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Upload lambda
        run: yarn deploy:test
